5GoInMul-Transcendence/ft_transcendence

front/src/app/(main)/layout.tsx
front/src/app/login/page.tsx
front/src/app/signup/page.tsx
front/src/component/PingPongAnimation/index.tsx
front/src/component/PingPongAnimation/styles.css

- layout 수정, pingpong animation 추가
- 레이아웃 안의 {children}이 전체 크기를 넘어가 스크롤이 생겨서 수정했습니다.
- ping pong animation 추가
- 회원가입 페이지 수정
- #20

Feat/pingpong animation mod layout#20

---

front/package-lock.json
front/package.json
front/src/app/api/README.md
front/src/app/api/friends/data.json
front/src/app/api/friends/route.ts
front/src/component/FriendList/index.tsx
front/src/types/IFriends.ts
front/src/types/IUser.ts
front/src/utils/fetcher.ts

- mockup data 생성
- axios를 사용한 swr fetcher 구현
- swr 로 mockup  데이터 불러오기
- npm i swr 추가 되었습니다
- axios 와 같은 경우 반환 값으로 promiss 함수를 전달합니다. 이 프로미스 함수에서 필요한 값 객체data만 리턴하는 fetcher를 만들었습니다
- 데이터 타입을 지정하는 tpyes 폴더를 만들고 인터페이스 파일을 선언 하였습니다! 
- #19

feat : mockup data 생성 및 axios, swr 세팅#19

---

front/src/app/(main)/chats/ChannelItem.tsx
front/src/app/(main)/chats/ChannelList.tsx
front/src/app/(main)/chats/[channelid]/ChatItem.tsx
front/src/app/(main)/chats/[channelid]/page.tsx
front/src/app/(main)/chats/layout.tsx
front/src/app/(main)/layout.tsx

- 채팅 페이지 뷰 구현
- 채팅 페이지 구현
- layout css 수정
- #36

Feat/chatting page#36

---

back/web-app/src/users/me/dto/game-record.dto.ts
back/web-app/src/users/me/dto/get-user-profile-res.dto.ts
back/web-app/src/users/me/dto/get-user-res.dto.ts
back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/user/user.module.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
마이 프로필 조회 구현 (GET /me)
[마이 프로필 조회](https://app.gitbook.com/o/q6D11IzK040l6FEcH24B/s/Y0RYPfXZv3onz6TL8qGR/api-reference/undefined-2/undefined-1)
- UserModule이 수정되었습니다.
- (+) MeController
- (+) MemoryUserService
- (+) MemoryUserProvider
- (+) Friend, Follower, Block 레퍼지토리
- MeController가 추가되었습니다.
- (+) getUser() : /me 요청을 처리합니다.
- #48

[Feat] API - 마이 프로필 조회 #48

---

back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/memoryuser/memory-user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 기존의 findUser() 메서드명을 수정하였습니다.
- MemoryUserService
(+) findUser -> findUserByUserId로 메서드 명이 수정되었습니다.
- #77

[Refactor] findUserByUserId 메서드명 수정 #77

---

back/web-app/src/users/me/dto/get-user-profile-by-nickname-req.dto.ts
back/web-app/src/users/me/dto/get-user-profile-by-nickname-res.dto.ts
back/web-app/src/users/me/me.controller.ts

- 상대방 프로필 조회 요청을 받을 메서드를 구현했습니다. (me.controller.getUserProfileByNickname())
- 상대방 프로필 조회는 마이 프로필 조회와 다르게 친구인지 블럭한 유저인지 체크해야합니다.
- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 상대방 프로필 조회
> 요청 성공
```javascript
{ 
"data":{
"id":1,
"nickname": 'donghyuk',
"avatar": '793506111257096042754805',
"gameRecord":"{
"win":10
"loss":10
"ladderLevel":10
"achievement":['10연승'] | []
}"
"isFriend": true|false,
"isBlock" : true|false,
},
"resStatus" :
{
"message": ""
}
}
```
<br>
> 요청 실패
```javascript
{ 
"data":{},
"resStatus" :
{
"message": "존재하지 않은 유저입니다."
}
}
```
<br>
- me.controller
(+) getUserProfileByNickname() // 상대방 프로필 조회 핸들러
- dto
(+) GetUserProfileByNicknameReqDto // 핸들러에서 필요한 dto
(+) GetUserProfileByNicknameResDto // 핸들러에서 …

[Feat] API - 상대방 프로필 조회 #50

---

back/web-app/src/main.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 서버 포트를 프론트와 다른 포트로 수정
- main.ts
- app.listen(8080);
- #74

[Refactor] WebConfig - Port 8080 수정 #74

---

back/web-app/src/login/login.controller.ts
back/web-app/src/signup/dto/signup-member-req.dto.ts
back/web-app/src/signup/signup.controller.ts
back/web-app/src/signup/signup.service.ts
back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/user/dto/create-member-user.dto.ts
back/web-app/src/users/user/user.module.ts
back/web-app/src/users/user/user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- member signup 구현, Member user 란 ID/password 를 사용하여 회원가입한 user 를 뜻한다.
- 자세한 것은 아래 38번 이슈에 정리 해뒀다.
- #38

[Feat] Member 회원가입 구현 완료

---

back/web-app/src/common/cors/cors.options.ts
back/web-app/src/main.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- Cors 구현
- corsOptions
- origin: 응답을 허용할 출처(origin)를 지정합니다.
origin은 Url을 가지며 Url은 Protocol, Host, Port을 포함합니다. 
ex) http://localhost:3000
- credentials: true라면 프론트엔드 자바스크립트 코드에 response 데이터를 노출합니다.
- methods: 리소스 접근을 허용할 요청 메소드를 지정합니다.
- #73

[Feat] WebSecure - Cors 구현 #73

---

back/web-app/src/app.module.ts
back/web-app/src/friend/dto/add-friend-req.dto.ts
back/web-app/src/friend/dto/add-friend-res.dto.ts
back/web-app/src/friend/dto/add-friend.dto.ts
back/web-app/src/friend/friend.controller.ts
back/web-app/src/friend/friend.module.ts
back/web-app/src/friend/friend.service.ts
back/web-app/src/users/user/user.module.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 친구 추가 API 구현
> 요청 성공
```
{ 
"data" :{
"id":1,
"nickname":'donghyuk',
"avatar":'793506111257096042754805',
"status":'online'|'offline'|'ingame'
},
"resStatus" :
{
"message": ""
}
}
```
> 요청 실패
```
{ 
"data" :{},
"resStatus" :
{
"message": "이미 추가된 유저입니다."
}
}
```
- exports
- MemoryUserService: Friend모듈에서 MemoryUserService를 주입받기 위해 추가했습니다.
- AddFriendDto: friendService.addFriend()의 인자 dto입니다.
- AddFriendReqDto: API 요청을 받기 위한 dto입니다.
- AddFriendResDto: API 응답을 보내기 위한 dto입니다.
- imports
- UserModule: FriendService에서 MemoryUserService를 주입받기 위해 추가했습니다.
- constructor()
- memoryUserService: 메모리 사용자를 조회하고 업데이트하기 위해 추가하였습니다.
- dataSource: typeorm의 트랜잭션 처리하고자 추가하였습니다.
- addFriend()
- …

[Feat] API - 친구 추가 #49

---

back/web-app/src/app.module.ts
back/web-app/src/auth/auth-info.ts
back/web-app/src/auth/auth.controller.ts
back/web-app/src/auth/auth.module.ts
back/web-app/src/auth/auth.service.ts
back/web-app/src/auth/dto/auth-mail-req.dto.ts
back/web-app/src/auth/dto/auth-mail.dto.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 메일 인증코드 전송
> 요청 성공
``` javascript
{ 
"data" :{},
"resStatus" :
{
"message": ""
}
}
```
> 요청 실패
``` javascript
{ 
"data" :{},
"resStatus" :
{
"message": "유효하지 않는 이메일입니다."
}
}
```
<br>
<br>
- imports
- MailModule: AuthService에서 인증 메일을 보내기 위해 추가하였습니다.
- 인증 코드 및 변경된 프로필 정보를 저장하는 객체입니다.
- twoFactor: 어떤 인증인지 저장합니다. 
exclude를 사용하여 Mail, Phone만 가져올 수 있도록 enum을 새로 정의했습니다.
- modifyValue: 변경할 프로필 정보를 저장합니다.
- code: 인증코드를 저장합니다.
- AuthService는 사용자 정보(메일, 휴대폰) 인증을 담당합니다. 
- authInfos: 유저별 인증정보를 저장합니다.
- authMail(): 메일로 인증코드를 전송하고 해당 유저에 대한 인증정보(코드, 변경할 메일)를 저장합니다.
- 메일 인증코드 전송 요청, 핸드폰 인증코드 전송 요청, 인증코드 확인 요청을 받습니다.
- 아직 mail에 대한 유효성 검사는 처리하지 않았습니다. (나중에 이슈를 만들 예정)
- #53

[Feat] API - 메일 인증코드 전송 #53

---

back/web-app/src/auth/auth.controller.ts
back/web-app/src/auth/auth.module.ts
back/web-app/src/auth/auth.service.ts
back/web-app/src/auth/dto/check-auth-code-req.dto.ts
back/web-app/src/auth/dto/check-auth-code.dto.ts
back/web-app/src/users/user/dto/update-user.dto.ts
back/web-app/src/users/user/user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
> 요청 성공
```
{ 
"data" :{},
"resStatus" :
{
"message": ""
}
}
```
> 요청 실패
```
{ 
"data" :{},
"resStatus" :
{
"message": "잘못된 인증코드입니다."
}
}
```
<br>
<br>
- imports
- UserModule 추가: 인증 코드 확인 후 사용자 프로필 정보를 업데이트하기 위해(UserService를 사용하기 위해) 포함하게 되었습니다.
- constructor()
- userService 추가
- checkAuthCode(): 인증코드 확인 로직
- 유효성 검사
- 인증코드 전송한 적이 있는지 확인합니다.
- 인증코드 일치여부를 확인합니다.
- 인증코드 일치시
- modifyValue 정보가 있는지 확인합니다.
- 만약 있다면, 인증방식(MAIL | PHONE)에 따라 유저 정보를 업데이트 합니다.
- 유저정보 업데이트 완료후 인증정보(AuthInfo)를 삭제합니다.
- checkAuthCode()
- '인증코드 확인'요청을 받는 핸들러를 구현하였습니다.
- constructor()
- memoryUserService 추가: 유저 프로필 정보를 업데이트할 때 DB업데이트 후 MemoryUser도 같이 업데이트하고자 추가하였습니다.
- updateUser()
- 사용자 업데이트 정보(dto)를 통해 …

[Feat] API - 인증코드 확인 #99

---

back/web-app/src/auth/auth.controller.ts
back/web-app/src/auth/auth.module.ts
back/web-app/src/auth/auth.service.ts
back/web-app/src/auth/dto/auth-phone-req.dto.ts
back/web-app/src/auth/dto/auth-phone.dto.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
> 요청 성공
```javascript
{ 
"data" :{},
"resStatus" :
{
"message": ""
}
}
```
> 요청 실패
```javascript
{ 
"data" :{},
"resStatus" :
{
"message": "핸드폰 번호가 올바르지 않습니다."
}
}
```
<br>
<br>
- imports
- SmsModule: smsService를 사용하여 문자전송을 보내고자 포함시키게 되었습니다.
- authPhone() 추가
- smsService를 통해 문자전송을 보내고 인증코드를 받습니다.
- 전달받은 인증코드와 현재 인증방식(phone), 그리고 인증성공시 수정할 프로필 정보(핸드폰 번호)를 메모리(AuthInfo)에 저장합니다.
- authPhone() 추가
- '핸드폰 인증코드 전송' API 요청을 받는 핸들러를 구현하였습니다.
- AuthPhoneReqDto
- AuthPhoneDto
<br>
- 핸드폰 인증코드 전송 요청
- #98

[Feat] API - 핸드폰 인증코드 전송 #98

---

back/web-app/src/auth/auth.controller.ts
back/web-app/src/auth/auth.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- conflict 수정 중 중괄호도 스윽 지워버린 부분을 수정했습니다.
- 수정 후 정상실행 확인했습니다!
-

[Fix] 중괄호 이슈

---

back/web-app/src/friend/dto/get-friends-info.dto.ts
back/web-app/src/friend/friend-info.ts
back/web-app/src/friend/friend.controller.ts
back/web-app/src/friend/friend.service.ts
back/web-app/src/users/memoryuser/memory-user.provider.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
> 요청 성공
<br>
- 반환할 친구 정보(id, nickname, avatar, status)를 담고 있습니다.
- getFriendsInfo() 추가
- 사용자 정보를 조회한 후, 사용자 친구리스트를 순회해 각 친구 정보를 가져옵니다.
- 가져온 친구 정보를 반환할 데이터 friendInfo로 변환합니다.
- friendInfo를 배열에 담아 반환합니다.
- @controller('friend') -> ('') 데코레이터 핸들러 경로 수정
- 친구 리스트 조회(/friendlist) 핸들러를 추가하기 위해 공백으로 수정하였습니다.
- getFriendsInfo()
- 친구 리스트 조회 요청을 처리하는 핸들러를 구현하였습니다.
- GetFriendsInfoDto
- 메모리 유저 초기화 부분에서 팔로워와 프렌즈의 정보가 서로 바껴 가져오는 이슈를 발견하였습니다.
해당 부분을 수정하였습니다. (친구 리스트 조회 요청을 보내면서 알게 되었습니다.)
<br>
- 친구 추가 후(donghyuk3), 친구 리스트 조회한 경우
- #54

[Feat] API - 친구 리스트 조회 #54

---

back/web-app/src/users/me/dto/update-nickname-req.dto.ts
back/web-app/src/users/me/dto/update-nickname.dto.ts
back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/memoryuser/dto/check-duplicate-nickname.dto.ts
back/web-app/src/users/memoryuser/memory-user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
> 요청 성공
```javascript
{ 
"data" :{},
"resStatus" :
{
"message": ""
}
}
```
> 요청 실패 
```javascript
{ 
"data" :{},
"resStatus" :
{
"message": "이미 사용중인 닉네임입니다."
}
}
```
<br>
<br>
- checkDuplicateNickname() 추가
- 닉네임 중복 여부를 확인합니다.
- 이미 닉네임이 존재할 경우 예외를 던집니다.
- constructor() 수정
- userService 추가: 사용자 프로필 정보를 업데이트하기 위해 사용됩니다.
- updateNickname() 추가
- '닉네임 수정' API 요청을 처리합니다.
- 닉네임을 업데이트 하기 전, 닉네임 중복여부를 확인합니다.
- 중복이 없을 경우 사용자 닉네임을 업데이트합니다.
- UpdateNicknameDto
- CheckDuplicateNicknameDto
<br>
- 중복된 닉네임인 경우
- 중복되지 않은 닉네임인 경우
- 닉네임 변경 후 마이 프로필 조회
- #52

[Feat] API - 닉네임 수정 #52

---

back/web-app/src/users/me/me.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- dto 미구현으로 주석되었던 상세 프로필 조회를 다시 복구하였습니다.
- 정상적으로 요청이 되는지 확인하였습니다.
- #111

[Chore] API 상세 프로필 조회 / 주석 제거 #111

---

back/web-app/src/users/me/dto/update-twofactor-req.dto.ts
back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/memoryuser/dto/check-available-twofactor.dto.ts
back/web-app/src/users/memoryuser/memory-user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
> 요청 성공
``` javascript
{ 
"data" :{},
"resStatus" :
{
"message": ""
}
}
```
> 요청 실패
``` javascript
{ 
"data" :{},
"resStatus" :
{
"message": "잘못된 요청입니다."
}
}
```
<br>
<br>
- checkAvailableTwoFactor() 
- 메서드 명은 'Available 이용 가능한'이라는 단어를 넣어 만들었습니다.
- mail을 선택하였을 경우 mail이 null 유무를 확인합니다.
- phone을 선태갛였을 경우 phone이 null인지 확인합니다.
- updateTwoFactor()
- 'twofactor 수정' API를 처리하는 핸들러를 구현했습니다.
- 이용 가능한 2FA인지 확인 후 사용자 정보를 업데이트합니다.
- UpdateTwofactorReqDto
- CheckAvailableTwofactorDto
<br>
- 사용자 정보 중 mail이 유효한 상태에서 twofactor를 mail로 수정 요청
- 사용자 정보 중 phone이 null 상태에서 twofactor를 phone으로 수정 요청
- #115

[Feat] API - twofactor 수정 #115

---

back/web-app/src/app.module.ts
back/web-app/src/users/memoryuser/memory-user.service.ts
back/web-app/tsconfig.json

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
```javascript
import _ from 'lodash';
_.cloneDeep(user); << 에러 발생
```
<br><br> 
`commonJS 모듈`을 `ES6 모듈 방식`으로 가져올 때 발생하는 문제입니다.
``` javascript
import _ from 'lodash';
_.cloneDeep(user); 
```
위 코드를 typescript에서 컴파일 할 경우, 
import하는 모듈들은  `ES6 모듈 방식`을 적용해 아래 코드로 변환합니다.
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const lodash_1 = require("lodash");
lodash_1.default.cloneDeep(user);
```
하지만 lodash 라이브러리는 `commonJS 모듈`이기에 (node에서 사용하는)
`lodash_1.default`가 정의되어 있지 않아 런타임에서 오류가 발생합니다.
<br>
typecript 공식 사이트에서는 모듈화 방식간에 호환성을 제공하고자
`esModuleInterop` 컴파일 옵션을 제공해줍니다. 
[tsconfig.json]
esModuleInterop = true 정의함으로써 위 문제를 해결하였습니다.
<br>
- MemoryUserService 수정
- import cloneDeep from 'lodash'
모든 객체를 가져오는 것이 아닌 …

[Fix] lodash 런타임 에러 해결 #118

---

back/web-app/src/signup/signup.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- Member user 가 데이터베이스에 생성될 때 메모리에도 추가
- #107

feat: add-memoryUser-at-createUser-in-signupMember#107

---

back/web-app/src/login/ft.strategy.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 필요 없는 데이터 삭제
- #131

refactor: 42 oauth 에 요청하는 필요 없는 정보 삭제#131

---

front/src/app/layout.tsx
front/src/component/Buttons/Button.tsx
front/src/component/Buttons/index.tsx
front/src/component/Input/index.tsx
front/src/component/Modal/AddFriend.tsx
front/src/component/Modal/AuthMail.tsx
front/src/component/Modal/AuthPhone.tsx
front/src/component/Modal/CreateChannel.tsx
front/src/component/Modal/EnterChannel.tsx
front/src/component/Modal/InvMatch.tsx
front/src/component/Modal/InvalidMsg.tsx
front/src/component/Modal/InvedMatch.tsx
front/src/component/Modal/SetChannel.tsx
front/src/component/Modal/SetNick.tsx
front/src/component/Modal/SetUser.tsx
front/src/component/Modal/index.tsx

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 모달 구현
- 리코일로 관리될 예정입니다. 추후 리코일 설치 & 리코일로 해당 모달 부르기
- 모달의 통일성을 위해 input 컴포넌트를 만들었습니다.
- 유효성 검사는 편의상 버튼 클릭시에 검사하도록 구현했습니다.
- buttons styled 70%에서 conflict가 나는데 일단 올렸쑴니더,,,
- #78

[Feat] modal 구현 #78

---

back/web-app/src/common/database/database.config.ts
back/web-app/src/login/login.controller.ts
docker/back/srcs/app/tools/app.sh
docker/back/srcs/docker-compose.yml

- npm start:dev -> npm start
- delete configServer DB_SCHEMA
- docker compose port 추가 및 network 연결
- 42oauth POST ->  GET 변경
- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- npm start:dev -> npm start
- delete configServer DB_SCHEMA
- docker compose port 추가 및 network 연결
- 42oauth POST ->  GET 변경
-

[Feat] api 테스트를 위한 도커세팅

---

back/web-app/src/login/login.controller.ts
back/web-app/src/login/login.module.ts
back/web-app/src/signup/signup.controller.ts
back/web-app/src/signup/signup.module.ts
back/web-app/src/signup/signup.service.ts
back/web-app/src/users/memoryuser/dto/get-user-by-nickname.dto.ts
back/web-app/src/users/memoryuser/memory-user.service.ts
back/web-app/src/users/user/dto/create-user.dto.ts
back/web-app/src/users/user/user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 회원가입 시 uuid 를 사용했던 지난 날을 회상하며... 이젠 아니야...
- 이젠 user + 8글자 랜덤 아이디라구!!!
- #148 
- #149

Feat/generate random id#149

---

front/package-lock.json
front/package.json
front/src/app/(main)/chats/ChannelItem.tsx
front/src/app/(main)/chats/[channelId]/ChannelEdit.tsx
front/src/app/(main)/chats/[channelId]/UserItem.tsx
front/src/app/(main)/chats/layout.tsx
front/src/app/(main)/layout.tsx
front/src/app/(main)/myprofile/edit/EditItem.tsx
front/src/app/(main)/myprofile/edit/page.tsx
front/src/app/layout.tsx
front/src/component/Input/index.tsx
front/src/component/Modal/AddFriend.tsx
front/src/component/Modal/CreateChannel.tsx
front/src/component/Modal/EnterChannel.tsx
front/src/component/Modal/InvedMatch.tsx
front/src/component/Modal/SetChannel.tsx
front/src/component/Modal/SetNick.tsx
front/src/component/Modal/SetUser.tsx
front/src/component/Modal/index.tsx
front/src/types/IUser.tsx
front/src/utils/recoil/atom.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- recoil 설치, modalState 아톰으로 모달상태관리
- 모달 적용 및 api
- 모달에 props를 넘길 수 있도록 수정
- #164

[Feat] modal 적용 및 api #164

---

back/web-app/src/users/user/user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 유저 회원가입시 프렌즈, 팔로워를 DB에 추가해주는 로직을 구현하였습니다.
- #170

[Feat] 유저 회원가입시 프렌즈, 팔로워 DB에 추가

---

back/web-app/src/common/cors/cors.options.ts
back/web-app/src/common/response/redirect-resource.enum.ts
back/web-app/src/login/login.controller.ts
back/web-app/src/users/user/user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- CORS Method 옵션을 `*`에서 `GET, POST, PUT, DELETE`으로 변경하였습니다.
- 유저 회원가입시 block 정보를 DB에 추가하는 로직을 작성하였습니다.
- 42 OAUTH 로그인 성공 후 리다이렉트 처리 로직을 작성하였습니다.
- #173

[Feat] 0830 API 테스트

---

back/web-app/src/session/session.middleware.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- maxage: 360000(6분) -> 3600000(1시간)
-  #182

[Fix] Session maxage 수정

---

front/src/app/(auth)/login/page.tsx
front/src/app/(main)/chats/ChannelItem.tsx
front/src/app/(main)/chats/ChannelList.tsx
front/src/app/(main)/chats/[channelId]/ChannelChatting.tsx
front/src/app/(main)/chats/[channelId]/ChannelEdit.tsx
front/src/app/(main)/chats/[channelId]/ChatItem.tsx
front/src/app/(main)/chats/[channelId]/page.tsx
front/src/app/(main)/layout.tsx
front/src/app/(main)/myprofile/edit/page.tsx
front/src/app/(main)/profile/[user]/page.tsx
front/src/app/api/channel/[channelId]/data.json
front/src/component/Modal/AuthMail.tsx
front/src/component/Modal/CreateChannel.tsx
front/src/component/Modal/EnterChannel.tsx
front/src/component/Modal/SetChannel.tsx
front/src/component/Modal/SetUser.tsx
front/src/types/IChannel.ts
front/src/utils/AxiosApiHadling.tsx
front/src/utils/recoil/atom.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 채널 update, delete 등 소켓 응답 구현
- 새로 들어오는 메시지인 recentMessage는 `recentMessageState` 리코일로 관리됩니다.
- `recentMessageState`를 구독하고 있는 컴포넌트는 `ChannelItem`과 `chats/[channelid/page`로 새로운 메시지의 `channelid`가 일치할 시 `ChannelItem` 중 My Channel의 recentMessage가 변경되고, `chats/[channelid]/page`에 새로운 메시지가 올라옵니다.
- profile 페이지의 DirectMessage 버튼 클릭 시 channel 생성 api를 요청합니다. `{name: null, mode: dm, password: null`
- 성공 시에는 응답으로 `channelid`를 받아 `/chats/[channelid]`로 페이지 이동을 해야합니다! (아직 안되어있음)
- `chats/[channelid]` 페이지의 컴포넌트 분리 `edit`이 `true`이면 `ChannelEdit` `false`이면 `ChannelChatting` 컴포넌트 보임
- 내 정보를 저장해두는 리코일이 하나 있으면 좋을 것 같습니다 ! 
- #189

[Feat] chatting socket#189

---

back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/channels/channel/channel.service.ts
back/web-app/src/channels/channel/dto/add-channel-res.dto.ts
back/web-app/src/channels/channel/dto/my-channels.dto.ts
back/web-app/src/channels/channel/dto/recent-message.dto.ts
back/web-app/src/channels/channel/entity/channel.entity.ts
back/web-app/src/channels/channel/entity/link-channel-to-user.entity.ts
back/web-app/src/channels/channel/entity/message.entity.ts
back/web-app/src/channels/channels.controller.ts
back/web-app/src/channels/channels.module.ts
back/web-app/src/channels/channels.service.ts
back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/user/entities/user.entity.ts
back/web-app/src/users/user/user.controller.ts
back/web-app/src/users/user/user.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 커밋 메시지에 파일 별로 자세하게 기술하였습니다!
- 채팅 페이지로 가게 되면 좌측엔 All, My 채널 리스트를 보여줍니다. All 채널은 생성된 모든 채널을 의미합니다.
- All 채널 중 자신이 생성했거나 기존에 이미 생성 된 방을 들어가게 되면 My 채널이 되게 됩니다.
- 채널 : 유저 = N : N 관계를 갖습니다. 이때 둘 줄 하나라도 개수가 늘어날 경우에 과도한 데이터를 담은 행이 추가 됩니다.
- 이를 방지하고, role 이라는 방 한 개 당 한 명의 유저에게 할당 되는 값을 추가하기 위해 LinkChannelToUser table 을 추가하여 1 : N : 1 관계를 형성했습니다.
- API 응답에서 요구하는 데이터를 위해 이후 유지 보수를 고려하여 설계하고, 각각의 테이블에서 알맞게 가져오는 것이 이번 풀리퀘의 핵심입니다.
- #147 
- #185

Feat/api get my channels#147

---

back/web-app/src/ladder/dto/find-ladder.dto.ts
back/web-app/src/ladder/dto/update-ladder.dto.ts
back/web-app/src/ladder/entities/ladder.entity.ts
back/web-app/src/ladder/ladder-level-table.ts
back/web-app/src/ladder/ladder.module.ts
back/web-app/src/ladder/ladder.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 사용자별 레더를 추가합니다.
- 게임 결과에 따라 레더 정보를 업데이트합니다.
게임 플레이에 따라 사용자의 레더 레벨 업데이트 할 수 있어야 합니다.
던전앤파이터의 결투장 등급표를 참고하여 레벨 디자인을 하였습니다.
(참고 이미지)
-  #206

[Feat] LadderService 구현

---

front/next.config.js
front/src/app/(auth)/2fa/page.tsx
front/src/app/(auth)/login/page.tsx
front/src/app/(main)/myprofile/edit/AuthSelect.tsx
front/src/app/(main)/myprofile/edit/page.tsx
front/src/app/game/page.tsx
front/src/app/layout.tsx
front/src/component/Modal/AuthMail.tsx
front/src/component/Modal/AuthPhone.tsx
front/src/component/Modal/SetNick.tsx
front/src/hooks/useSwrFetcher.ts
front/src/utils/AxiosApiHadling.tsx

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- qa때 발생했던 문제점들을 수정하였습니다
- axios error handling 코드 수정
- 2fa 페이지 인증 성공시 route push 추가
- 로그인 페이지 에러 핸들링
- 닉네임 메일 번호 수정시 mutate걸어서 바로 업데이트 
- #221

Fix/qa test#221

---

back/web-app/src/auth/dto/auth-mail-req.dto.ts
back/web-app/src/auth/dto/auth-phone-req.dto.ts
back/web-app/src/common/response/fail/http-exception.filter.ts
back/web-app/src/common/validation/nickname.validation.ts
back/web-app/src/common/validation/phonenumber.validation.ts
back/web-app/src/friend/dto/add-friend-req.dto.ts
back/web-app/src/main.ts
back/web-app/src/signup/dto/signup-member-req.dto.ts
back/web-app/src/users/me/dto/update-nickname-req.dto.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 닉네임 유효성 검사
- 알파벳 또는 숫자인지 확인합니다.
- 문자열의 길이가 2~12 범위에 속하는지 확인합니다. 
- 핸드폰 유효성 검사
- 모두 숫자인지 확인합니다.
- 010으로 시작하는지 확인합니다.
- 총 11글자인지 확인합니다.
- 멤버 회원가입시, 아이디 유효성 검사
- 알파벳 또는 숫자인지 확인합니다.
- 문자열의 길이가 2 ~ 12 범위에 속하는지 확인합니다.
- 멤버 회원가입시, 패스워드 유효성 검사
- 아스키 코드인지 확인합니다.
- 문자열의 길이가 8 ~ 15 범위에 속하는지 확인합니다.
- 이메일 유효성 검사
- 프론트와 테스트
- 회원가입시, 아이디 패스워드 유효성 검사를 마쳤습니다.
- 프로필 페이지에서, 닉네임, 이메일, 핸드폰 변경시 유효성 검사를 마쳤습니다.
- #103 
- #102 
- #97

[Feat] Validation - 유효성 검사

---

back/web-app/src/main/mainuser/main-user.service.ts

* UpdateUser
- 메인 유저의 프로퍼티를 업데이트할 때 null인지 확인 후 데이터를 업데이트 합니다.
- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- MainUserService.updateUser() 메서드에서 메인유저가 소켓에 끊겼을 경우
undefined상태로 에러가 발생해 수정합니다.
- #213

[fix] MainUserService 수정

---

back/web-app/src/achievement/achievement.module.ts
back/web-app/src/ladder/ladder.module.ts
back/web-app/src/users/me/dto/game-record.dto.ts
back/web-app/src/users/me/me.controller.ts
back/web-app/src/users/me/me.module.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
-  마이프로필(/me)에서 래더 승,패,레벨,업적 정보를 목데이터로 반환하던 것을 수정하였습니다.
- #214
- #172

[Refactor] API - 마이 프로필

---

back/web-app/src/common/image/image.config.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
현재 코드에서 이미지 크기 제한처리가 작동하지 않습니다.
multeroption.fileFilter(): (request, file, callback)
- `file`인자가 size를 제공해 주지않아 조건문 처리가 되질 않았습니다.
- multeroption.limit를 정의하여 해결하였습니다.
- #223

[Fix] API - 아바타 업데이트 수정 (파일 사이즈 제한)

---

back/web-app/src/app.module.ts
back/web-app/src/auth/auth.controller.ts
back/web-app/src/auth/auth.module.ts
back/web-app/src/common/response/redirect-resource.enum.ts
back/web-app/src/login/login.controller.ts
back/web-app/src/login/login.module.ts
back/web-app/src/login/login.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- O-Auth 또는 member 로그인시, 2fa가 활성화 되어있을 경우 '/auth'페이지로 리다이렉트 합니다.
- #68

[Feat] API - 로그인 인증페이지 리다이렉트

---

back/web-app/src/users/me/me.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 닉네임을 수정할 경우 팔로워들에게 업데이트된 닉네임을 전송합니다.
- 프론트와 테스트 완료하였습니다.
- 닉네임 변경후 상대방한테 변경된 닉네임을 전송합니다.
- #120

[Refactor] API - 닉네임 수정시 친구정보 업데이트

---

back/game-app/src/game/game-process-unit.ts
back/game-app/src/game/game.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 무조건 플레이어 1이 이기는 부분을 수정하였습니다.

[Refactor] Game 결과 로직 수정

---

back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/channels/channel/channel.service.ts
back/web-app/src/channels/channel/dto/update-role-at-leave-owner-req.dto.ts
back/web-app/src/channels/channel/dto/update-role-in-link.dto.ts
back/web-app/src/channels/channel/link-channel-to-user.service.ts
back/web-app/src/channels/channels.controller.ts
back/web-app/src/channels/channels.module.ts
back/web-app/src/message/message.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 자세한 사항은 커밋 메시지 확인 부탁드립니다.
- param 으로 주어진 id 로 확인
- session 을 통해 확인
- 메시지 삭제
- ban 목록 삭제
- mode 에 따른 차이점
- public, protected, private 는 나갈 때 나가는 사람 혼자만 있다면 채널 폭파
- dm 은 한 명만 나가도 채널 폭파
- 나머지 한 명의 link 도 삭제
- admin, user 가 나갈 시 단순히 채널에서 나가짐
- owner 가 나갈 시 다음 owner 가 결정 되어야 한다.
- admin 중 하나? admin 이 없다면?
- user 중 랜덤 하나? user 는 owner 가 나가더라도 사람 수가 1명 이상일 때 진행하기 때문에 무조건 존재한다.
- #196

Feat/api leave channel#196

---

back/web-app/src/ladder/dto/find-ladder-return.dto.ts
back/web-app/src/ladder/ladder.service.ts
back/web-app/src/users/me/dto/game-record.dto.ts
back/web-app/src/users/me/me.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 승보다 패가 많을 경우, 래더 레벨이 0이 되었습니다.
최소 래더 레벨이 1이 되도록 수정하였습니다.
- 이제 래더 레벨(1)이 아닌 래더 레벨 이름(10급)이 출력되도록 수정하였습니다.

[Refactor] API - 마이 프로필 조회 (래더 레벨 수정)

---

back/web-app/src/channels/channel/channel-setting.service.ts
back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/channels/channel/channel.service.ts
back/web-app/src/channels/channel/dto/get-channel-information-res.dto.ts
back/web-app/src/channels/channel/dto/update-channel-setting-req.dto.ts
back/web-app/src/channels/channel/exception/channel-exception.service.ts
back/web-app/src/channels/channel/link-channel-to-user.service.ts
back/web-app/src/channels/channels.module.ts
back/web-app/src/common/hash/hash.service.ts

- 채널이 존재하고, 채널에 존재하는 유저라면 누구든지 해당 채널 정보를 가져올 수 있다.
- #239 
- #240

feat: api-get-channel-information, updateChannelSetting 구현 완료#239

---

back/web-app/src/game/game.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 이제 게임 종료 후 게임 히스토리를 저장합니다.

[Refactor] 게임 종료 후 히스토리 추가

---

back/web-app/src/app.module.ts
back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/channels/channels.module.ts
back/web-app/src/chat/chat.gateway.ts
back/web-app/src/chat/chat.module.ts
back/web-app/src/chat/chat.service.ts
back/web-app/src/chat/dto/add-all-channel-res.dto.ts
back/web-app/src/chat/dto/add-my-channel-res.dto.ts
back/web-app/src/chat/dto/delete-channel-res.dto.ts
back/web-app/src/chat/dto/send-chat-message.dto.ts
back/web-app/src/chat/dto/update-all-channel.dto.ts
back/web-app/src/chat/dto/update-my-channel-res.dto.ts
back/web-app/src/chat/dto/update-my-channel.dto.ts
back/web-app/src/chat/enums/chat-event.enum.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- localhost:10002/chat 으로 소켓 접속이 가능합니다.
- AllChannel 정보를 업데이트합니다.
- MyChannel 정보를 업데이트합니다.
- 채널에 속한 모든 유저들에게 브로드 캐스트 해줍니다.
- #256

[Feat] ChatServer 구현 

---

back/web-app/src/main/main.gateway.ts
back/web-app/src/main/match/dto/invite-match.dto.ts
back/web-app/src/main/match/match-group.ts
back/web-app/src/main/match/match.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 이제 상대방 프로필에서 매치 신청이 가능합니다.
- 매치 신청
- 상대방이 초대 받을 수 있는 상태인지 확인합니다.
- 초대가 가능하다면, 마치 큐에서 서로 만난 것과 동일하게 처리됩니다.
- 매치 신청 거절
- 매치 신청을 거절했다면 원래는 큐로 다시 넣어줬어습니다. 그 부분만 분기처리 해줬습니다.
- #260

[Feat] API - 매치 신청 (re)

---

back/web-app/src/common/image/image.config.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 기존에 이미지 확장자를 jpg, jpeng, png로 제한을 하였다.
- 다른 확장자를 업로드하면 에러메시지는 출력하였으나 그대로 파일을 저장하는 문제를 해결했다.
- #266

[Refactor] 이미지 업로드 업데이트 (확장자 필터 문제 해결)

---

back/web-app/src/common/response/redirect-resource.enum.ts
back/web-app/src/login/login.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 로그인시 메인 페이지에서 마이프로필 수정 페이지로 리다이렉트 되도록 수정하였습니다.
- 도커환경에서는 'localhost:3000'이 아닌 'nextjs:3000'으로 이동해야하기 때문에 환경변수로 분리하였습니다.
- env, env.prod FRONT_URL을 설정하면 됩니다.
- #244

[Refactor] 로그인시 리다이렉트 위치 수정

---

back/web-app/src/auth/auth.controller.ts
back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/login/login.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
commit 내용을 참고바랍니다.

[Fix] 0920 - TEST 

---

back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/chat/chat.service.ts
back/web-app/src/chat/dto/send-chat-message.dto.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 채팅 메시지를 보낼 때, `id`를  'userId'에서 'channelId'로 변경하였습니다.

[Refactor] 채팅 메시지 업데이트

---

back/web-app/src/common/cors/cors.options.ts
back/web-app/src/login/login.controller.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- corsOptions의 origin 값을 수정하였습니다.
- 도커, 로컬 환경에 맞는 origin을 대입할 수 있도록 env파일에 의존하여 값을 대입합니다.
- #274

[Refactor] Cors 옵션 업데이트

---

back/web-app/src/channels/channel/channel.service.ts
back/web-app/src/channels/channel/dto/recent-message.dto.ts
back/web-app/src/chat/chat.module.ts
back/web-app/src/chat/chat.service.ts
back/web-app/src/chat/dto/add-my-channel-res.dto.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 자세한 구현은 commit 메시지 참고
- #282

Feat/update recent message#282

---

back/web-app/src/channels/channel/channel-setting.service.ts
back/web-app/src/channels/channel/channel.service.ts
back/web-app/src/channels/channel/dto/get-channel-information-res.dto.ts
back/web-app/src/channels/channel/dto/recent-message-at-enter.dto.ts
back/web-app/src/channels/channel/dto/recent-message.dto.ts
back/web-app/src/chat/chat.service.ts
back/web-app/src/chat/dto/update-my-channel-res.dto.ts
back/web-app/src/message/message.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 아래 이슈 확인해주세요!
- #284

Refactor/add avatar in message#284

---

back/web-app/src/main/match/match.service.ts

매치를 보낸 사람이 자신일 경우 그대로 return합니다.
- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 자신에게 매치를 보내는 경우 이를 무시하도록 수정하였습니다.

[Refactor] 매치 신청 수정 (자신에게 보내는 경우)

---

back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/main/match/match.service.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
커밋 내용을 확인해주세요~

[Refactor] DM 생성시 상대방에게도 UpdateMyChannel 전송

---

.gitignore
back/web-app/src/channels/channel/channel.controller.ts
back/web-app/src/channels/channel/dto/authenticate-password-req.dto.ts
back/web-app/src/channels/channel/dto/create-protected-channel-req.dto.ts
back/web-app/src/channels/channel/dto/create-public-channel-req.dto.ts
back/web-app/src/channels/channel/dto/send-message-req.dto.ts
back/web-app/src/channels/channel/pipes/channel-name.pipe.ts
back/web-app/src/channels/channel/pipes/channel-password.pipe.ts
back/web-app/src/message/pipes/message-length.pipe.ts
back/web-app/src/session/auth.middleware.ts

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- message 최대 입력을 255 자로 제한. 그러나 프론트에서 특정 글자가 넘어가면 페이지를 넘어가 버려서 프론트에서도 제한하기로 했다.
- protected 채널 생성, 비밀번호 변경 시 비밀번호 길이 제한 4~12
- #56

Feat/add pipe about message length and password in channel#56

---

front/src/app/(main)/chats/ChannelItem.tsx
front/src/app/(main)/myprofile/edit/page.tsx
front/src/component/Modal/index.tsx

- [Feat]
- [Docs]
- [Chore]
- [Refactor]
- [Fix]
- 10mb 넘어가는 이미지 막기
- 밴 되었을 때 프론트에서 에러 메시지 띄우기 
-

feat : 10mb 크기 넘어가는 파일 처리 및 ban 될 때 에러메시지 띄우기
